source("https://bioconductor.org/biocLite.R")
biocLite("EBImage")
install.packages("shiny")
install.packages("shinyjs")
install.packages("abind")
install.packages("jpeg")

library(shiny)
library(EBImage)
library(shinyjs)
library(abind)
library(jpeg)
